name: desktop_webview_auth
description: This package enables OAuth flows on desktop via webview for Firebase and other OAuth providers.
version: 0.0.12
homepage: https://github.com/invertase/flutter_desktop_webview_auth

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DesktopWebviewAuthPlugin
      linux:
        pluginClass: DesktopWebviewAuthPlugin
      windows:
        pluginClass: DesktopWebviewAuthPlugin
      ios:
        pluginClass: DesktopWebviewAuthPlugin
      android:
        package: com.example.desktop_webview_auth
        pluginClass: DesktopWebviewAuthPlugin
      web:
        pluginClass: DesktopWebviewAuthWeb
        fileName: desktop_webview_auth_web.dart

false_secrets:
  - /README.md
  - /example/lib/main.dart
  - /example/macos/Runner/GoogleService-Info.plist
